packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.2.4
  react-dom: ^19.2.4
  vite: ^8.0.5
  typescript: ^6.0.2
  '@sentry/react': ^10.40.0
  '@sentry/vite-plugin': ^5.1.1

ignoredBuiltDependencies:
  - unrs-resolver
