name: lint-action

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Install Node.js
        uses: BCSDLab/.github/.github/actions/setup-node@v1
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check lint
        env:
          CI: true
        run: pnpm lint

      - name: Check build
        env:
          CI: true
          VITE_API_PATH: https://example.com
          VITE_SENTRY_ENABLED: false
        run: pnpm build
